name: Benchmark execution time comparison with the main branch

on:
  pull_request:
    branches: [main]

jobs:
  benchmark-exec-time:
    if: contains( github.event.pull_request.labels.*.name, 'benchmark-exec-time' )
    runs-on: ubuntu-latest

    steps:
    - name: Setup Linux env
      run: |
        sudo apt -y update
        sudo apt install jq podman libsystemd-dev librust-libdbus-sys-dev libseccomp-dev

    - name: Setting rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    
    - name: Checkout to PR branch
      uses: actions/checkout@v2

    - name: Building PR branch
      run: |
        ./build.sh --release

    - name: Uploading PR build to artifact
      uses: actions/upload-artifact@v2
      with:
        name: pr-youki
        path: ./youki

    - name: Checkout to main branch
      uses: actions/checkout@v2
      with:
        ref: main
      
    - name: Building main branch
      run: | 
        ./build.sh --release
        mv ./youki ./main_youki

    - name: Downloading PR build from artifact
      uses: actions/download-artifact@v2
      with:
        name: pr-youki
        path: ./pr_youki

    - name: Preparing benchmark bundle
      run: |
        mkdir -p benchmark_exec_bundle/rootfs
        cd benchmark_exec_bundle
        sudo bash -c 'podman export $(podman create busybox) | tar -C rootfs -xvf -'
        ../main_youki spec 
        sed -i 's/"sh"/"sh", "-c", "echo Hi, my PID is $$; echo Bye Bye"/' config.json
        sed -i 's/"terminal": true/"terminal": false/' config.json
          
    - name: Installing hyperfine
      run: |
        curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest \
        | jq -r '.assets[] | select(.name? | match("hyperfine-musl_.*_amd64.deb")) | .browser_download_url' \
        | wget -qi -
        sudo dpkg -i *.deb

    - name: Running benchmark
      run: |
        hyperfine --show-output --prepare 'sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
        --warmup 10 \
        --min-runs 100 \
        'sudo ./main_youki run -b benchmark_exec_bundle main_youki && sudo ./main_youki delete -f main_youki' \
        'sudo ./pr_youki run -b benchmark_exec_bundle pr_youki && sudo ./pr_youki delete -f pr_youki'
