name: Benchmark execution time compare with the main branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark-exec-time:
    if: ${{ github.event.label.name == 'benchmark-exec-time' }}

    runs-on: ubuntu-latest

    steps:
    - name: Setup Linux building env
      run: |
        sudo apt -y update
        sudo apt install jq libsystemd-dev librust-libdbus-sys-dev libseccomp-dev

    - name: Setting rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.56.1
        override: true
        profile: minimal
    
    - name: Checkout to PR branch
      uses: actions/checkout@v2

    - name: Building PR branch
      run: |
        ./build.sh --release

    - name: Uploading PR build to artifact
      uses: actions/upload-artifact@v2
      with:
        name: pr-youki
        path: ./youki

    - name: Checkout to main branch
      uses: actions/checkout@v2
      with:
        ref: main
      
    - name: Building main branch
      run: | 
        ./build.sh --release
        mv ./youki ./main_youki

    - name: Downloading PR build from artifact
      uses: actions/download-artifact@v2
      with:
        name: pr-youki
        path: ./pr-youki
          
    - name: Installing hyperfine
      run: |
        curl -s https://api.github.com/repos/sharkdp/hyperfine/releases/latest \
        | jq -r '.assets[] | select(.name? | match("hyperfine-musl_.*_amd64.deb")) | .browser_download_url' \
        | wget -qi -
        sudo dpkg -i *.deb

    - name: Showing everything 
      run: |
       ls -la
       hyperfine --version
